### ISSUE TITLE
Changing values in modal window - if click outside, closes and loses values

### ISSUE THREAD

**Issue by DrDanPrice** [DataAnalyticsinStudentHands/FormBuilder#42]
Not sure how the modal windows open/close, but if I don't save or cancel, but click on the next field, the modal window closes and my changes are lost. 
I'd prefer that it doesn't let me click outside the modal window.

**Comment by CarlSteven** [comment]
So here's what I ran into:
- On popover closure: we can opt to not rollback changes and instead save them.
- Disable closing of popover when another component's popover opens up.

In either scenario, the popover will close when the component is being moved. I think this is because it has nothing to attach to?

**Comment by CarlSteven** [comment]
I've thrown in an autosave function on popover closing. They must hit the "cancel button" to get a rollback. The "Save" buttons have been changed to "Close".

This may help alleviate this issue.
