### ISSUE TITLE
Top section header should have a title

### ISSUE THREAD

**Issue by DrDanPrice** [DataAnalyticsinStudentHands/FormBuilder#63]
it looks like the section titles and expands/collapses, but doesn't have any text in the pink rectangle

**Comment by CarlSteven** [comment]
If user adds a section divider as first element of form, then they can name it. This probably doesn't make a whole lot of sense.

In order to eliminate confusion, I am adding in a section form component as the first element when the form builder interface is opened on every new form created. Users can then remove or rename this section as they please.
